name: "Reporte de bug (ES)"
description: Reporta un problema o regresión
labels: ["bug", "lang:es", "needs triage"]
body:
  - type: input
    id: version
    attributes:
      label: Versión de ReProxm
      placeholder: v0.1.0
    validations: { required: true }
  - type: textarea
    id: what-happened
    attributes:
      label: ¿Qué ocurrió?
      description: Pasos para reproducir, comportamiento actual vs esperado.
    validations: { required: true }
  - type: textarea
    id: logs
    attributes:
      label: Logs / salidas relevantes
      render: shell
  - type: dropdown
    id: area
    attributes:
      label: Área
      options:
        - sync_lxc_backups.sh
        - backup_host.sh
        - check_disk.sh
        - install.sh
        - docs