name: "Bug report (EN)"
description: Report a problem or regression
labels: ["bug", "lang:en", "needs triage"]
body:
  - type: input
    id: version
    attributes:
      label: ReProxm version
      placeholder: v0.1.0
    validations: { required: true }
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Steps to reproduce, actual vs expected behavior.
    validations: { required: true }
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs / outputs
      render: shell
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - sync_lxc_backups.sh
        - backup_host.sh
        - check_disk.sh
        - install.sh
        - docs