name: "Feature request (EN)"
description: Propose an improvement or new capability
labels: ["enhancement", "lang:en", "needs triage"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What pain does this feature address?
    validations: { required: true }
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe UX/CLI flags, configs, outputs.
    validations: { required: true }
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Clear, testable outcomes.